name: Packer CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  packer-fmt-validate:
    name: Packer Format & Validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://releases.hashicorp.com/packer/1.9.1/packer_1.9.1_linux_amd64.zip
          unzip packer_1.9.1_linux_amd64.zip
          sudo mv packer /usr/local/bin/packer

      - name: Check Packer formatting
        run: |
          packer fmt -check -diff src/main/scripts

      - name: Initialize packer
        run: |
          packer init src/main/scripts

      - name: Create dummy artifact if not present
        run: |
          if [ ! -f dummy.zip ]; then
            echo "Dummy file" > dummy.zip
          fi

      - name: Validate Packer template
        run: |
          packer validate src/main/scripts
